# Generated by Django 5.0.14 on 2025-11-27 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0005_club_metadata_cid_club_nft_serial_commonnft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('token', models.CharField(default='HBAR', max_length=50)),
                ('tier', models.IntegerField(default='COMMON', verbose_name={'COMMON': {'access_type': 'Free', 'privileges': 'Basic yield farms from JBLB partners', 'quantity': 300}, 'EPIC': {'access_type': 'Staking', 'privileges': 'Premium yield farms; higher reward multipliers', 'quantity': 50}, 'LEGENDARY': {'access_type': 'Staking', 'privileges': 'Exclusive farms; high-APY and cross-chain access', 'quantity': 30}, 'RARE': {'access_type': 'Staking', 'privileges': 'Intermediate yield access; requires subscription', 'quantity': 120}})),
                ('duration_seconds', models.IntegerField(default=604800)),
                ('velocity', models.IntegerField(default=2)),
                ('stake_per_player_usd', models.FloatField(default=100)),
                ('total_pool_usd', models.FloatField(default=0)),
                ('treasury_cut', models.FloatField(default=0)),
                ('winner_prize', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('active', 'Active'), ('settling', 'Settling'), ('finished', 'Finished')], default='waiting', max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_nft_token_id', models.CharField(blank=True, max_length=100, null=True)),
                ('chain', models.CharField(choices=[('hedera', 'Hedera'), ('anoma', 'Anoma')], default='Hedera', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('staked_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('initial_value', models.FloatField(default=0.0)),
                ('current_value', models.FloatField(default=0.0)),
                ('roi', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('jsparks_earned', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='PlayerToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Token',
                'verbose_name_plural': 'Player Tokens',
                'db_table': 'player_tokens',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('tokens', models.JSONField(default=list)),
                ('total_weight', models.FloatField(default=0.0)),
                ('initial_value', models.FloatField(default=100.0, help_text='Initial value is starting from 100')),
                ('current_value', models.FloatField(default=100.0)),
                ('oracle_source', models.CharField(default='pyth', editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='clubs.club')),
            ],
        ),
    ]
