# Generated by Django 5.0.14 on 2025-10-26 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_wallet', models.CharField(max_length=255)),
                ('config', models.JSONField()),
                ('initial_value', models.FloatField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('token', models.CharField(default='ETH', max_length=50)),
                ('tier', models.IntegerField(default=1)),
                ('duration_seconds', models.IntegerField(default=3600)),
                ('velocity', models.IntegerField(default=2)),
                ('stake_amount', models.FloatField(default=100)),
                ('status', models.CharField(default='waiting_for_players', max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staked_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('roi', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('jsparks_earned', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='battles.battle')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clubs.club')),
                ('staked_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'players',
                'unique_together': {('user', 'active_battle')},
            },
        ),
        migrations.CreateModel(
            name='PlayerToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to='battles.player')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.token')),
            ],
            options={
                'verbose_name': 'Player Token',
                'verbose_name_plural': 'Player Tokens',
                'db_table': 'player_tokens',
                'unique_together': {('player', 'token')},
            },
        ),
    ]
