# Generated by Django 5.0.14 on 2025-11-17 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
        ('clubs', '0005_club_metadata_cid_club_nft_serial_commonnft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='config',
        ),
        migrations.AddField(
            model_name='basket',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='basket',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basket',
            name='current_value',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='basket',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='oracle_source',
            field=models.CharField(default='pyth', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='basket',
            name='tokens',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='basket',
            name='total_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='chain',
            field=models.CharField(choices=[('hedera', 'Hedera'), ('anoma', 'Anoma')], default='Hedera', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='nft_token_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='creator_wallet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='initial_value',
            field=models.FloatField(default=100.0, help_text='Initial value is starting from 100'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='tier',
            field=models.IntegerField(default='COMMON', verbose_name={'COMMON': {'access_type': 'Free', 'privileges': 'Basic yield farms from JBLB partners', 'quantity': 300}, 'EPIC': {'access_type': 'Staking', 'privileges': 'Premium yield farms; higher reward multipliers', 'quantity': 50}, 'LEGENDARY': {'access_type': 'Staking', 'privileges': 'Exclusive farms; high-APY and cross-chain access', 'quantity': 30}, 'RARE': {'access_type': 'Staking', 'privileges': 'Intermediate yield access; requires subscription', 'quantity': 120}}),
        ),
    ]
