# Generated by Django 5.0.14 on 2025-11-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chain',
            field=models.CharField(choices=[('hedera', 'Hedera'), ('anoma', 'Anoma')], default='Hedera', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='nft_token_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
