# Generated by Django 5.0.14 on 2025-11-27 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battles', '0001_initial'),
        ('blockchain', '0001_initial'),
        ('clubs', '0005_club_metadata_cid_club_nft_serial_commonnft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='active_battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_players', to='battles.battle'),
        ),
        migrations.AddField(
            model_name='player',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='battles.basket'),
        ),
        migrations.AddField(
            model_name='player',
            name='battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='battles.battle'),
        ),
        migrations.AddField(
            model_name='player',
            name='staked_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.token'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playertoken',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to='battles.player'),
        ),
        migrations.AddField(
            model_name='playertoken',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.token'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'battle')},
        ),
        migrations.AlterUniqueTogether(
            name='playertoken',
            unique_together={('player', 'token')},
        ),
    ]
