# Generated by Django 5.0.14 on 2025-11-19 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_remove_basket_config_basket_club_basket_creator_and_more'),
        ('clubs', '0005_club_metadata_cid_club_nft_serial_commonnft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='stake_amount',
            new_name='stake_per_player_usd',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='nft_token_id',
            new_name='reward_nft_token_id',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'battle')},
        ),
        migrations.AddField(
            model_name='battle',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='battle',
            name='total_pool_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='treasury_cut',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner_prize',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='battles.basket'),
        ),
        migrations.AddField(
            model_name='player',
            name='battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='battles.battle'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='initial_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='battle',
            name='duration_seconds',
            field=models.IntegerField(default=604800),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('active', 'Active'), ('settling', 'Settling'), ('finished', 'Finished')], default='waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='battle',
            name='token',
            field=models.CharField(default='HBAR', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='active_battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_players', to='battles.battle'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
    ]
