# Generated by Django 5.0.14 on 2025-11-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_player_chain_player_is_verified_player_nft_token_id'),
        ('clubs', '0004_club_description_club_members_alter_club_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='tier',
            field=models.IntegerField(default='COMMON', verbose_name={'COMMON': {'access_type': 'Free', 'privileges': 'Basic yield farms from JBLB partners', 'quantity': 300}, 'EPIC': {'access_type': 'Staking', 'privileges': 'Premium yield farms; higher reward multipliers', 'quantity': 50}, 'LEGENDARY': {'access_type': 'Staking', 'privileges': 'Exclusive farms; high-APY and cross-chain access', 'quantity': 30}, 'RARE': {'access_type': 'Staking', 'privileges': 'Intermediate yield access; requires subscription', 'quantity': 120}}),
        ),
    ]
