# Generated by Django 5.0.14 on 2025-11-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_basket_club_alter_battle_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='initial_value',
            field=models.FloatField(default=5),
        ),
    ]
