# Generated by Django 5.0.14 on 2025-11-10 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_alter_basket_initial_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='config',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='initial_value',
        ),
        migrations.AddField(
            model_name='basket',
            name='tokens',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='basket',
            name='total_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='basket',
            name='creator_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL),
        ),
    ]
