# Generated by Django 5.0.14 on 2025-11-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0006_basket_creator_basket_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='initial_value',
            field=models.FloatField(default=100.0),
        ),
    ]
