# Generated by Django 5.0.14 on 2025-11-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0007_basket_initial_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
