# Generated by Django 5.0.14 on 2025-12-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='token_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
