# Generated by Django 5.0.14 on 2025-12-07 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_emailoutbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='waitlist.waitlist'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='html',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='username',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
