# Generated by Django 5.0.14 on 2025-10-26 22:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('network', models.CharField(choices=[('ETHEREUM', 'Ethereum'), ('SOLANA', 'Solana'), ('AVALANCHE', 'Avalanche'), ('HEDERA', 'Hedera'), ('ANOMA', 'Anoma')], max_length=50)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'tokens',
            },
        ),
    ]
