# Generated by Django 5.0.14 on 2026-01-06 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waitlist', '0005_add_user_field_to_waitlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('verified_referrals', models.PositiveIntegerField(default=0)),
                ('pending_referrals', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Referral Statistics',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('verified_referrals', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_referrals', '-total_earnings'],
                'indexes': [models.Index(fields=['rank'], name='referrals_l_rank_0b78f5_idx'), models.Index(fields=['verified_referrals'], name='referrals_l_verifie_2d659b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_referrals', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_referrals', to=settings.AUTH_USER_MODEL)),
                ('waitlist_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_network', to='waitlist.waitlist')),
            ],
            options={
                'indexes': [models.Index(fields=['referrer'], name='referrals_r_referre_3fa4d6_idx'), models.Index(fields=['referred_user'], name='referrals_r_referre_a7ee72_idx'), models.Index(fields=['is_verified'], name='referrals_r_is_veri_5c6393_idx')],
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
    ]
