# Generated by Django 5.0.14 on 2025-11-02 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='access_type',
            field=models.CharField(default='Free', max_length=50),
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('COMMON', [('quantity', 300), ('access_type', 'Free'), ('privileges', 'Basic yield farms from JBLB partners')]), ('RARE', [('quantity', 120), ('access_type', 'Staking'), ('privileges', 'Intermediate yield access; requires subscription')]), ('EPIC', [('quantity', 50), ('access_type', 'Staking'), ('privileges', 'Premium yield farms; higher reward multipliers')]), ('LEGENDARY', [('quantity', 30), ('access_type', 'Staking'), ('privileges', 'Exclusive farms; high-APY and cross-chain access')])], default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='privileges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='tier',
            field=models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='owner_wallet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
