# Generated by Django 5.0.14 on 2025-11-17 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_description_club_members_alter_club_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='metadata_cid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='nft_serial',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CommonNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.BigIntegerField(unique=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('club', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
    ]
